### ISSUE TITLE
Magnetic Field Data

### ISSUE THREAD

**Issue by torydebra** [qleonardolp/xsens_mtw_driver-release#1]
Hi, thanks for your work!

Have you any plan to provide also magnetic field data through a [mangeticfield message](http://docs.ros.org/en/melodic/api/sensor_msgs/html/msg/MagneticField.html)? 
Did you have encounter any issues in providing this?

**Comment by qleonardolp** [comment]
> 
Hi, sorry to take so long to answer! You can get magnetic data storing 'packet->calibratedMagneticField()' on a `std::vector<XsVector>`.

**Comment by torydebra** [comment]
Hi, thanks anyway :D

I am not using these sensors anymore, but it may be useful for the future!
